apiVersion: v1
kind: Service
metadata:
  name: kanban-proxy
  namespace: foodme
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kanban-proxy
  namespace: foodme
subsets:
- addresses:
  - ip: 10.0.26.107  # IP do pod kanban atual
  ports:
  - port: 3000
    protocol: TCP