apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-app
  namespace: kanban
  labels:
    app: kanban-app
spec:
  replicas: 1  # Reduced from 2 to 1 to avoid state issues without shared DB
  selector:
    matchLabels:
      app: kanban-app
  template:
    metadata:
      labels:
        app: kanban-app
    spec:
      containers:
      - name: kanban-app
        image: 440744259713.dkr.ecr.us-east-1.amazonaws.com/kanban-app:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5