apiVersion: v1
kind: Service
metadata:
  name: kanban-proxy
  namespace: foodme
spec:
  type: ClusterIP
  selector:
    app: kanban-app  # This will automatically find kanban pods
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP