apiVersion: v1
kind: Service
metadata:
  name: kanban-app-service
  namespace: kanban
  labels:
    app: kanban-app
spec:
  selector:
    app: kanban-app
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
