apiVersion: v1
kind: Service
metadata:
  name: kanban-proxy
  namespace: foodme
spec:
  type: ExternalName
  externalName: kanban-app-service.kanban.svc.cluster.local
  ports:
  - port: 80
    targetPort: 3000  # Fixed: Application runs on port 3000, not 80